version: "3"

name: investor_app
services:
  postgresdb:
    container_name: investor-postgresdb
    image: postgres
    restart: always
    ports:
      - ${DOCKER_PG_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_volume:/var/lib/postgresql
    networks:
      - investor_network

  backend:
    container_name: investor-api
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    depends_on:
      - postgresdb
    ports:
      - ${DOCKER_NEST_PORT}:3001
    networks:
      - investor_network

  frontend:
    container_name: investor-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - ${DOCKER_NEXT_PORT}:3000
    networks:
      - investor_network

volumes:
  pg_volume:

networks:
  investor_network:
    name: investor_network
