name: Deploy to server
run-name: deploying
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_TIMEWEB_SWEATCLUB_ID_RSA_PRIVATE_KEY }}
          port: 22
          script: |
            cp /var/www/env-files/investor/.env /var/www/pttrulez-subdomains/investor-full/.env
            cp /var/www/env-files/investor/.env.package.database /var/www/pttrulez-subdomains/investor-full/packages/database/.env.docker
            cp /var/www/env-files/investor/.env.app.next-client /var/www/pttrulez-subdomains/investor-full/apps/client/.env.docker
            cp /var/www/env-files/investor/.env.app.nest-server /var/www/pttrulez-subdomains/investor-full/apps/server/.env
            cd /var/www/pttrulez-subdomains/investor-full
            git pull
            docker-compose up -d --build
